version: "3.9"
services:

  home-assistant:
    image: homeassistant/raspberrypi4-homeassistant:2021.11.2
    ports:
      - "8123:8123"
    volumes:
      - "/nfs/docker/homeassistant:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "/sys/class/thermal/thermal_zone0/temp:/thermal/thermal_zone0/temp"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/nfs/docker/homeassistant/docker/run:/etc/services.d/home-assistant/run"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "UMASK=007"
      - "PACKAGES=iputils"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mosquitto:
    image: eclipse-mosquitto:2.0.13
    volumes:
      - "/nfs/docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "/nfs/docker/mosquitto/data:/mosquitto/data"
      - "/nfs/docker/mosquitto/log:/mosquitto/log"
    ports:
      - "1883:1883"
      - "9001:9001"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  pihole:
    image: pihole/pihole:2021.10.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      - "TZ=Europe/Prague"
    volumes:
      - "/nfs/docker/pihole/pihole:/etc/pihole/"
      - "/nfs/docker/pihole/dnsmasq:/etc/dnsmasq.d/"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  room-assistant:
    image: mkerix/room-assistant:2.19.1
    networks:
      - "outside"
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /nfs/docker/roomassistant/config:/room-assistant/config
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  influxdb:
    image: arm32v7/influxdb:1.8
    volumes:
      - "/nfs/docker/influxdb:/var/lib/influxdb"
    ports:
      - "8086:8086"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mariadb:
    image: linuxserver/mariadb:10.5.12
    volumes:
      - "/nfs/docker/mariadb:/config"
    ports:
      - "3306:3306"
    environment:
      - "TZ=Europe/Prague"
      - "MYSQL_ROOT_PASSWORD=raspberry"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    
  agent:
    image: portainer/agent:2.10.0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
    networks:
      - agent_network
    deploy:
      mode: global

  portainer:
    image: portainer/portainer-ce:2.9.2
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - "/nfs/docker/portainer:/data"
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

networks:
  outside:
    name: "host"
    external: true
  agent_network:
    driver: overlay
    attachable: true