version: "3.5"

services:

  zwave:
    image: zwavejs/zwavejs2mqtt:6.5.2
    container_name: zwave
    volumes:
      - "/nfs/docker/zwavejs/store:/usr/src/app/store"
      - "/run/lock:/run/lock/zwave-js"
    environment:
      ZWAVEJS_LOCK_DIRECTORY: "/run/lock/zwave-js"
    devices:
      - "/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave"
    ports:
      - "8091:8091"
      - "3000:3000"
    restart: unless-stopped
    
  octoprint:
    image: octoprint/octoprint:1.7
    container_name: octoprint
    volumes:
      - "/nfs/docker/octoprint:/octoprint"
    environment:
      ENABLE_MJPG_STREAMER: "false"
    devices:
      - "/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyACM0"
    ports:
      - "80:80"
    restart: unless-stopped