version: "3.9"
services:

  home-assistant:
    image: homeassistant/raspberrypi4-homeassistant:2021.11.3
    ports:
      - "8123:8123"
    volumes:
      - "/nfs/docker/homeassistant:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "/sys/class/thermal/thermal_zone0/temp:/thermal/thermal_zone0/temp"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/nfs/docker/homeassistant/docker/run:/etc/services.d/home-assistant/run"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "UMASK=007"
      - "PACKAGES=iputils"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
      labels:
        - "diun.enable=true"
        - "diun.watch_repo=true"
        - "diun.max_tags=5"
        - "diun.include_tags=^\\d{4}\\.\\d{1,2}\\.\\d{1,2}$$"

  mosquitto:
    image: eclipse-mosquitto:2.0.13
    volumes:
      - "/nfs/docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "/nfs/docker/mosquitto/data:/mosquitto/data"
      - "/nfs/docker/mosquitto/log:/mosquitto/log"
    ports:
      - "1883:1883"
      - "9001:9001"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "diun.enable=true"
        - "diun.watch_repo=true"
        - "diun.max_tags=5"
        - "diun.include_tags=^\\d{1,2}\\.\\d{1,2}\\.\\d{0,2}$$"

  pihole:
    image: pihole/pihole:2021.10.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      - "TZ=Europe/Prague"
    volumes:
      - "/nfs/docker/pihole/pihole:/etc/pihole/"
      - "/nfs/docker/pihole/dnsmasq:/etc/dnsmasq.d/"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "diun.enable=true"
        - "diun.watch_repo=true"
        - "diun.max_tags=5"
        - "diun.include_tags=^\\d{4}\\.\\d{1,2}\\.\\d{1,2}$$"

  room-assistant:
    image: mkerix/room-assistant:2.19.1
    networks:
      - "outside"
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /nfs/docker/roomassistant/config:/room-assistant/config
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
      labels:
        - "diun.enable=true"
        - "diun.watch_repo=true"
        - "diun.max_tags=5"
        - "diun.include_tags=^\\d{1,2}\\.\\d{1,2}\\.\\d{0,2}$$"

  influxdb:
    image: arm32v7/influxdb:1.8
    volumes:
      - "/mnt/ssd/docker/influxdb:/var/lib/influxdb"
    ports:
      - "8086:8086"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==raspberrypi-2b1"
      labels:
        - "diun.enable=true"
        - "diun.watch_repo=true"
        - "diun.max_tags=5"
        - "diun.include_tags=^\\d{1,2}\\.\\d{1,2}\\.\\d{0,2}$$"

  mariadb:
    image: linuxserver/mariadb:10.5.12
    volumes:
      - "/mnt/ssd/docker/mariadb:/config"
    ports:
      - "3306:3306"
    environment:
      - "TZ=Europe/Prague"
      - "MYSQL_ROOT_PASSWORD=raspberry"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==raspberrypi-2b1"
      labels:
        - "diun.enable=true"
        - "diun.watch_repo=true"
        - "diun.max_tags=5"
        - "diun.include_tags=^\\d{1,2}\\.\\d{1,2}\\.\\d{0,2}$$"
    
  agent:
    image: portainer/agent:2.10.0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
    networks:
      - agent_network
    deploy:
      mode: global
      labels:
        - "diun.enable=true"
        - "diun.watch_repo=true"
        - "diun.max_tags=5"
        - "diun.include_tags=^\\d{1,2}\\.\\d{1,2}\\.\\d{0,2}$$"

  portainer:
    image: portainer/portainer-ce:2.9.2
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - "/nfs/docker/portainer:/data"
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
      labels:
        - "diun.enable=true"
        - "diun.watch_repo=true"
        - "diun.max_tags=5"
        - "diun.include_tags=^\\d{1,2}\\.\\d{1,2}\\.\\d{0,2}$$"

  chronograf:
    image: chronograf:1.9.1
    volumes:
      - "/nfs/docker/chronograf:/var/lib/chronograf"
    ports:
      - "8888:8888"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "diun.enable=true"
        - "diun.watch_repo=true"
        - "diun.max_tags=5"
        - "diun.include_tags=^\\d{1,2}\\.\\d{1,2}\\.\\d{0,2}$$"

  diun:
    image: crazymax/diun:4.20.1
    command: serve
    volumes:
      - "/nfs/docker/diun:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Prague"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_FIRSTCHECKNOTIF=true"
      - "DIUN_PROVIDERS_SWARM=true"
      - "DIUN_NOTIF_MQTT_SCHEME=mqtt"
      - "DIUN_NOTIF_MQTT_HOST=192.168.11.100"
      - "DIUN_NOTIF_MQTT_PORT=1883"
      - "DIUN_NOTIF_MQTT_CLIENT=DIUN"
      - "DIUN_NOTIF_MQTT_TOPIC=diun/docker_version"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      labels:
        - "diun.enable=true"
        - "diun.watch_repo=true"
        - "diun.max_tags=5"
        - "diun.include_tags=^\\d{1,2}\\.\\d{1,2}\\.\\d{0,2}$$"

networks:
  outside:
    name: "host"
    external: true
  agent_network:
    driver: overlay
    attachable: true