version: "3.5"

services:
 
  esphome:
    image: esphome/esphome:latest
    container_name: esphome
    volumes:
      - "/home/pi/docker/esphome:/config"
    network_mode: "host"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.max_tags=5"
      - "diun.include_tags=^\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$$"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - "/nfs/docker/grafana:/var/lib/grafana"
    ports:
      - "3000:3000"
    user: "1000"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.max_tags=5"
      - "diun.include_tags=^\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$$"
    restart: unless-stopped