version: "3.5"

services:

  deconz:
    image: deconzcommunity/deconz:2.13.03
    container_name: deconz
    volumes:
      - "/nfs/docker/deconz:/opt/deCONZ"
      - "/etc/localtime:/etc/localtime:ro"
    devices:
      - "/dev/ttyACM0"
    network_mode: "host"
    environment:
      DECONZ_VNC_MODE: "0"
      DECONZ_VNC_PORT: "5901"
    restart: unless-stopped
    
  unifi-controller:
    image: jacobalberty/unifi:v7
    container_name: unifi-controller
    ports:
      - "8443:8443"
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
    volumes:
      - "/nfs/docker/unifi-controller:/unifi"
    environment:
      - "TZ=Europe/Prague"
    restart: unless-stopped