version: "3.5"

services:
  home-assistant:
    image: homeassistant/raspberrypi4-homeassistant:stable
    container_name: home-assistant
    volumes:
      - "/home/pi/docker/homeassistant:/config"
      - "/home/pi/media:/media"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      PUID: "1000"
      PGID: "1000"
      UMASK: "007"
    network_mode: "host"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.max_tags=10"
      - "diun.include_tags=^\\d{4}\\.\\d{1,2}\\.\\d{1,2}$$"
    depends_on:
      - "influxdb"
      - "home-assistant-mariadb"
      - "deconz"
      - "openzwave"
    restart: always

  deconz:
    image: marthoc/deconz:latest
    container_name: deconz
    volumes:
      - "/home/pi/docker/deconz:/root/.local/share/dresden-elektronik/deCONZ"
      - "/etc/localtime:/etc/localtime:ro"
    devices:
      - "/dev/ttyACM0"
    network_mode: "host"
    environment:
      DECONZ_VNC_MODE: "0"
      DECONZ_VNC_PORT: "5901"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.max_tags=10"
      - "diun.include_tags=^\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$$"
    restart: always

  openzwave:
    image: openzwave/ozwdaemon:latest
    container_name: openzwave
    security_opt:
      - seccomp:unconfined
    devices:
      - "/dev/serial/by-id/usb-0658_0200-if00"
    volumes:
      - "/home/pi/docker/openzwave:/opt/ozw/config"
    ports:
      - "1983:1983"
    environment:
      MQTT_SERVER: "192.168.11.100"
      USB_PATH: "/dev/serial/by-id/usb-0658_0200-if00"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.max_tags=10"
      - "diun.include_tags=^build-\\d{1,4}$$"
    restart: always

  influxdb:
    image: library/influxdb:latest
    container_name: influxdb
    volumes:
      - "/home/pi/docker/influxdb:/var/lib/influxdb"
    ports:
      - "8086:8086"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.max_tags=10"
      - "diun.include_tags=^\\d{1,2}\\.\\d{1,2}\\.\\d{0,2}$$"
    restart: always

  home-assistant-mariadb:
    image: jsurf/rpi-mariadb:latest
    container_name: home-assistant-mariadb
    volumes:
      - "/home/pi/docker/mariadb:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "pi"
    labels:
      - "diun.enable=true"
    restart: always

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/pi/docker/portainer:/data"
    ports:
      - "9000:9000"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.max_tags=10"
      - "diun.include_tags=^\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$$"
    restart: always
    
  minidlna:
    image: vladgh/minidlna:latest
    container_name: minidlna
    volumes:
      - "/home/pi/media:/media"
    network_mode: "host"
    environment:
      MINIDLNA_FRIENDLY_NAME: "Rpi4DLNA"
      MINIDLNA_MEDIA_DIR: "/media"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.max_tags=10"
      - "diun.include_tags=^\\d{1,2}\\.\\d{1,2}$$"
    restart: always

  esphome:
    image: esphome/esphome:latest
    container_name: esphome
    volumes:
      - "/home/pi/docker/esphome:/config"
    network_mode: "host"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.max_tags=10"
      - "diun.include_tags=^\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$$"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - "/home/pi/docker/grafana:/var/lib/grafana"
    ports:
      - "3000:3000"
    user: "1000"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.max_tags=10"
      - "diun.include_tags=^\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$$"
    restart: always

  diun:
    image: crazymax/diun:latest
    container_name: diun
    volumes:
      - "/home/pi/docker/diun:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Prague"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true"
      - "DIUN_WATCH_FIRSTCHECKNOTIF=true"
      - "DIUN_NOTIF_MQTT_SCHEME=mqtt"
      - "DIUN_NOTIF_MQTT_HOST=192.168.11.100"
      - "DIUN_NOTIF_MQTT_PORT=1883"
      - "DIUN_NOTIF_MQTT_CLIENT=DUIN"
      - "DIUN_NOTIF_MQTT_TOPIC=diun/docker_version"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.max_tags=10"
      - "diun.include_tags=^\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$$"
    restart: always